name: skyprogram workflow
on: [push]
jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      name: run flake8
      uses: suo/flake8-github-action@releases/v1
      with:
        chekName: 'flake8_py3'
      env:
        GITHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: docker build
        run: docker build -t michaelrodionov/skyprogram_on_server:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker login
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: docker push
        run: docker push michaelrodionov/skyprogram_on_server:$GITHUB_REF_NAME-$GITHUB_RUN_ID
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: render configs
        run: |
          mkdir skyprogram_deploy
          cat docker-compose-ci.yaml | envsubst > skyprogram_deploy/docker-compose.yaml
      - name: copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "skyprogram_deploy/docker-compose.yaml"
          target: "skyprogram_app_ci"
          strip_components: 1
      - name: deploy skyprogram
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd skyprogram_app_ci
            echo ${{ secrets.PASSWORD }} | sudo -S docker-compose up -d